apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.js: |
    window.REACT_APP_SERVICE_LIST="word_frequency,chapter_title,format_check,chapter_summarization,page_count,table_of_content,citation,table_figure_detection,grammar";
    window.REACT_APP_BACKEND_HOST="http://backend.example.com";