apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REACT_APP_SERVICE_LIST: "word_frequency,chapter_title,format_check,chapter_summarization,page_count,table_of_content,citation,table_figure_detection"
  REACT_APP_BACKEND_HOST: "http://34.133.48.234:32000/"