apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-title-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-title
  template:
    metadata:
      labels:
        app: chapter-title
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-title
        image: daniel135dang/chapter_title:latest
        ports:
        - containerPort: 5001
        env:
          - name: APP_NAME
            value: "chapter_title"

          - name: POSTGRES_NAME
            value: "chapter_title"               
        
        envFrom:
          - configMapRef:
              name: services-config

        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: chapter-title-service
spec:
  selector:
    app: chapter-title
  ports:
    - name: chapter-title
      protocol: TCP
      port: 5001
      targetPort: 5001