apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-summarization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-summarization
  template:
    metadata:
      labels:
        app: chapter-summarization
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-summarization
        image: daniel135dang/chapter_summarization:latest
        ports:
        - containerPort: 5006
        env:
          - name: APP_NAME
            value: "chapter_summarization"

          - name: POSTGRES_NAME
            value: "chapter_summarization"               
        
        envFrom:
          - configMapRef:
              name: services-config

        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: chapter-summarization-service
spec:
  selector:
    app: chapter-summarization
  ports:
    - name: chapter-summarization
      protocol: TCP
      port: 5006
      targetPort: 5006