apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-summarization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-summarization
  template:
    metadata:
      labels:
        app: chapter-summarization
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-summarization
        image: daniel135dang/chapter_summarization:1.0.0-53
        ports:
        - containerPort: 5006
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "chapter_summarization"

          - name: POSTGRES_NAME
            value: "chapter_summarization"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-title-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-title
  template:
    metadata:
      labels:
        app: chapter-title
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-title
        image: daniel135dang/chapter_title:1.0.0-53
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "chapter_title"

          - name: POSTGRES_NAME
            value: "chapter_title"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citation
  template:
    metadata:
      labels:
        app: citation
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: citation
        image: daniel135dang/citation:1.0.0-53
        ports:
        - containerPort: 5007
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "citation"

          - name: POSTGRES_NAME
            value: "citation"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format-check
  template:
    metadata:
      labels:
        app: format-check
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: format-check
        image: daniel135dang/format_check:1.0.0-53
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "format_check"

          - name: POSTGRES_NAME
            value: "format_check"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-count-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-count
  template:
    metadata:
      labels:
        app: page-count
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: page-count
        image: daniel135dang/page_count:1.0.0-53
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "page_count"

          - name: POSTGRES_NAME
            value: "page_count"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-of-content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-of-content
  template:
    metadata:
      labels:
        app: table-of-content
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: table-of-content
        image: daniel135dang/table_of_content:1.0.0-53
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "table_of_content"

          - name: POSTGRES_NAME
            value: "table_of_content"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-frequency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-frequency
  template:
    metadata:
      labels:
        app: word-frequency
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: word-frequency
        image: daniel135dang/word_frequency:1.0.0-53
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "word_frequency"

          - name: POSTGRES_NAME
            value: "word_frequency"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  rest: rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      volumes:
      - rest: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - rest: rest
        image: daniel135dang/rest:1.0.0-53
        ports:
        - containerPort: 5008
        volumeMounts:
        - rest: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - rest: APP_NAME
            value: "rest"

          - rest: POSTGRES_NAME
            value: "rest"               
        
        envFrom:
          - configMapRef:
              rest: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  client: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      volumes:
      - client: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - client: client
        image: daniel135dang/client:1.0.0-53
        ports:
        - containerPort: 5009
        volumeMounts:
        - client: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - client: APP_NAME
            value: "client"

          - client: POSTGRES_NAME
            value: "client"               
        
        envFrom:
          - configMapRef:
              client: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  chapter_summarization: chapter_summarization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter_summarization
  template:
    metadata:
      labels:
        app: chapter_summarization
    spec:
      volumes:
      - chapter_summarization: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - chapter_summarization: chapter_summarization
        image: daniel135dang/chapter_summarization:1.0.0-53
        ports:
        - containerPort: 5010
        volumeMounts:
        - chapter_summarization: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - chapter_summarization: APP_NAME
            value: "chapter_summarization"

          - chapter_summarization: POSTGRES_NAME
            value: "chapter_summarization"               
        
        envFrom:
          - configMapRef:
              chapter_summarization: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  chapter_title: chapter_title-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter_title
  template:
    metadata:
      labels:
        app: chapter_title
    spec:
      volumes:
      - chapter_title: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - chapter_title: chapter_title
        image: daniel135dang/chapter_title:1.0.0-53
        ports:
        - containerPort: 5011
        volumeMounts:
        - chapter_title: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - chapter_title: APP_NAME
            value: "chapter_title"

          - chapter_title: POSTGRES_NAME
            value: "chapter_title"               
        
        envFrom:
          - configMapRef:
              chapter_title: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  format_check: format_check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format_check
  template:
    metadata:
      labels:
        app: format_check
    spec:
      volumes:
      - format_check: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - format_check: format_check
        image: daniel135dang/format_check:1.0.0-53
        ports:
        - containerPort: 5012
        volumeMounts:
        - format_check: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - format_check: APP_NAME
            value: "format_check"

          - format_check: POSTGRES_NAME
            value: "format_check"               
        
        envFrom:
          - configMapRef:
              format_check: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  page_count: page_count-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page_count
  template:
    metadata:
      labels:
        app: page_count
    spec:
      volumes:
      - page_count: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - page_count: page_count
        image: daniel135dang/page_count:1.0.0-53
        ports:
        - containerPort: 5013
        volumeMounts:
        - page_count: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - page_count: APP_NAME
            value: "page_count"

          - page_count: POSTGRES_NAME
            value: "page_count"               
        
        envFrom:
          - configMapRef:
              page_count: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  table_of_content: table_of_content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table_of_content
  template:
    metadata:
      labels:
        app: table_of_content
    spec:
      volumes:
      - table_of_content: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - table_of_content: table_of_content
        image: daniel135dang/table_of_content:1.0.0-53
        ports:
        - containerPort: 5014
        volumeMounts:
        - table_of_content: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - table_of_content: APP_NAME
            value: "table_of_content"

          - table_of_content: POSTGRES_NAME
            value: "table_of_content"               
        
        envFrom:
          - configMapRef:
              table_of_content: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  word_frequency: word_frequency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word_frequency
  template:
    metadata:
      labels:
        app: word_frequency
    spec:
      volumes:
      - word_frequency: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - word_frequency: word_frequency
        image: daniel135dang/word_frequency:1.0.0-53
        ports:
        - containerPort: 5015
        volumeMounts:
        - word_frequency: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - word_frequency: APP_NAME
            value: "word_frequency"

          - word_frequency: POSTGRES_NAME
            value: "word_frequency"               
        
        envFrom:
          - configMapRef:
              word_frequency: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  table_figure_detection: table_figure_detection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table_figure_detection
  template:
    metadata:
      labels:
        app: table_figure_detection
    spec:
      volumes:
      - table_figure_detection: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - table_figure_detection: table_figure_detection
        image: daniel135dang/table_figure_detection:1.0.0-53
        ports:
        - containerPort: 5016
        volumeMounts:
        - table_figure_detection: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - table_figure_detection: APP_NAME
            value: "table_figure_detection"

          - table_figure_detection: POSTGRES_NAME
            value: "table_figure_detection"               
        
        envFrom:
          - configMapRef:
              table_figure_detection: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  grammar: grammar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grammar
  template:
    metadata:
      labels:
        app: grammar
    spec:
      volumes:
      - grammar: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - grammar: grammar
        image: daniel135dang/grammar:1.0.0-53
        ports:
        - containerPort: 5017
        volumeMounts:
        - grammar: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - grammar: APP_NAME
            value: "grammar"

          - grammar: POSTGRES_NAME
            value: "grammar"               
        
        envFrom:
          - configMapRef:
              grammar: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  postgresql: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
      - postgresql: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - postgresql: postgresql
        image: daniel135dang/postgresql:1.0.0-53
        ports:
        - containerPort: 5018
        volumeMounts:
        - postgresql: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - postgresql: APP_NAME
            value: "postgresql"

          - postgresql: POSTGRES_NAME
            value: "postgresql"               
        
        envFrom:
          - configMapRef:
              postgresql: services-config
---