apiVersion: apps/v1
kind: Deployment
metadata:
  postgresql: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
      - postgresql: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - postgresql: postgresql
        image: daniel135dang/postgresql:1.0.0-52
        ports:
        - containerPort: 5018
        volumeMounts:
        - postgresql: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - postgresql: APP_NAME
            value: "postgresql"

          - postgresql: POSTGRES_NAME
            value: "postgresql"               
        
        envFrom:
          - configMapRef:
              postgresql: services-config
---