
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-summarization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-summarization
  template:
    metadata:
      labels:
        app: chapter-summarization
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-summarization
        image: daniel135dang/chapter-summarization: 1.0.0-83
        ports:
        - containerPort: 6002
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "chapter-summarization"

          - name: POSTGRES_NAME
            value: "chapter-summarization"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-title-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-title
  template:
    metadata:
      labels:
        app: chapter-title
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: chapter-title
        image: daniel135dang/chapter-title: 1.0.0-83
        ports:
        - containerPort: 6003
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "chapter-title"

          - name: POSTGRES_NAME
            value: "chapter-title"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-count-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-count
  template:
    metadata:
      labels:
        app: page-count
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: page-count
        image: daniel135dang/page-count: 1.0.0-83
        ports:
        - containerPort: 6004
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "page-count"

          - name: POSTGRES_NAME
            value: "page-count"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-of-content-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-of-content
  template:
    metadata:
      labels:
        app: table-of-content
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: table-of-content
        image: daniel135dang/table-of-content: 1.0.0-83
        ports:
        - containerPort: 6005
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "table-of-content"

          - name: POSTGRES_NAME
            value: "table-of-content"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-frequency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-frequency
  template:
    metadata:
      labels:
        app: word-frequency
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: word-frequency
        image: daniel135dang/word-frequency: 1.0.0-83
        ports:
        - containerPort: 6006
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "word-frequency"

          - name: POSTGRES_NAME
            value: "word-frequency"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citation
  template:
    metadata:
      labels:
        app: citation
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: citation
        image: daniel135dang/citation: 1.0.0-83
        ports:
        - containerPort: 6007
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "citation"

          - name: POSTGRES_NAME
            value: "citation"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-figure-detection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-figure-detection
  template:
    metadata:
      labels:
        app: table-figure-detection
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: table-figure-detection
        image: daniel135dang/table-figure-detection: 1.0.0-83
        ports:
        - containerPort: 6008
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "table-figure-detection"

          - name: POSTGRES_NAME
            value: "table-figure-detection"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grammar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grammar
  template:
    metadata:
      labels:
        app: grammar
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: grammar
        image: daniel135dang/grammar: 1.0.0-83
        ports:
        - containerPort: 6009
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "grammar"

          - name: POSTGRES_NAME
            value: "grammar"               
        
        envFrom:
          - configMapRef:
              name: services-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format-check
  template:
    metadata:
      labels:
        app: format-check
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: format-check
        image: daniel135dang/format-check: 1.0.0-83
        ports:
        - containerPort: 6010
        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: APP_NAME
            value: "format-check"

          - name: POSTGRES_NAME
            value: "format-check"               
        
        envFrom:
          - configMapRef:
              name: services-config
---