apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: format-check
  template:
    metadata:
      labels:
        app: format-check
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: format-check
        image: daniel135dang/format_check:latest
        ports:
        - containerPort: 5002
        env:
          - name: APP_NAME
            value: "format_check"

          - name: POSTGRES_NAME
            value: "format_check"               
        
        envFrom:
          - configMapRef:
              name: services-config

        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: format-check-service
spec:
  selector:
    app: format-check
  ports:
    - name: format-check
      protocol: TCP
      port: 5002
      targetPort: 5002