apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-count-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-count
  template:
    metadata:
      labels:
        app: page-count
    spec:
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: page-count
        image: daniel135dang/page_count:latest
        ports:
        - containerPort: 5003
        env:
          - name: APP_NAME
            value: "page_count"

          - name: POSTGRES_NAME
            value: "page_count"               
        
        envFrom:
          - configMapRef:
              name: services-config

        volumeMounts:
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: page-count-service
spec:
  selector:
    app: page-count
  ports:
    - name: page-count
      protocol: TCP
      port: 5003
      targetPort: 5003