apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: client-frontend
        tier: frontend
    spec:
      containers:
      - name: client
        image: daniel135dang/client:1.0.0-67
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-config-volume
          mountPath: /app/config.js
          subPath: config.js
          readOnly: true
      volumes:
      - name: app-config-volume
        configMap:
          name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-backend
      tier: backend
  template:
    metadata:
      labels:
        app: rest-backend
        tier: backend
    spec:
      volumes:
      - name: rest-file
        persistentVolumeClaim:
          claimName: rest-file-pvc
      - name: google-credentials
        secret:
          secretName: google-credentials
      containers:
      - name: rest-backend
        image: daniel135dang/rest:1.0.0-12
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: rest-file
          mountPath: /app/rest/files
        - name: google-credentials
          mountPath: /app/google_credentials.json
          subPath: google_credentials.json
          readOnly: true
        env:
          - name: PORT
            value: "5000"
          - name: APP_NAME
            value: "rest"
          - name: HOST
            value: "rest-service"
          - name: RABBITMQ_HOST
            value: "amqp://rabbitmq:5672"
          - name: RABBITMQ_FILE_LOCATION_EXCHANGE
            value: "uploaded_file_location"
          - name: RABBITMQ_OUTPUT_LOCATION_EXCHANGE
            value: "output_location"
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: POSTGRES_HOST
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: POSTGRES_DB
          - name: ROOT_DIR
            value: "/app"
          - name: REACT_APP_SERVICE_LIST
            value: "word_frequency,chapter_title,format_check,chapter_summarization,page_count,table_of_content,citation,table_figure_detection,grammar"
          - name: GUIDELINES_LIST
            value: "chapter_title,format_check,page_count"
          - name: GOOGLE_CLOUD_STORAGE_BUCKET
            valueFrom:
              configMapKeyRef:
                name: services-config
                key: GOOGLE_CLOUD_STORAGE_BUCKET
---
apiVersion: v1
kind: Service
metadata:
  name: client-frontend-service
  labels:
    app: client-frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: client-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: rest-backend
    tier: backend
spec:
  type: NodePort
  selector:
    app: rest-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30010