
apiVersion: v1
kind: Service
metadata:
  name: chapter-summarization-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6002'
spec:
  selector:
    app: chapter-summarization
  ports:
    - name: chapter-summarization
      protocol: TCP
      port: 6002
      targetPort: 6002
---
apiVersion: v1
kind: Service
metadata:
  name: chapter-title-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6003'
spec:
  selector:
    app: chapter-title
  ports:
    - name: chapter-title
      protocol: TCP
      port: 6003
      targetPort: 6003
---
apiVersion: v1
kind: Service
metadata:
  name: page-count-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6004'
spec:
  selector:
    app: page-count
  ports:
    - name: page-count
      protocol: TCP
      port: 6004
      targetPort: 6004
---
apiVersion: v1
kind: Service
metadata:
  name: citation-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6005'
spec:
  selector:
    app: citation
  ports:
    - name: citation
      protocol: TCP
      port: 6005
      targetPort: 6005
---
apiVersion: v1
kind: Service
metadata:
  name: table-figure-detection-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6006'
spec:
  selector:
    app: table-figure-detection
  ports:
    - name: table-figure-detection
      protocol: TCP
      port: 6006
      targetPort: 6006
---
apiVersion: v1
kind: Service
metadata:
  name: grammar-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6007'
spec:
  selector:
    app: grammar
  ports:
    - name: grammar
      protocol: TCP
      port: 6007
      targetPort: 6007
---
apiVersion: v1
kind: Service
metadata:
  name: format-check-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6008'
spec:
  selector:
    app: format-check
  ports:
    - name: format-check
      protocol: TCP
      port: 6008
      targetPort: 6008
---
apiVersion: v1
kind: Service
metadata:
  name: word-frequency-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6009'
spec:
  selector:
    app: word-frequency
  ports:
    - name: word-frequency
      protocol: TCP
      port: 6009
      targetPort: 6009
---
apiVersion: v1
kind: Service
metadata:
  name: table-of-content-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '6010'
spec:
  selector:
    app: table-of-content
  ports:
    - name: table-of-content
      protocol: TCP
      port: 6010
      targetPort: 6010
---